//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCode.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCode.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Project name=&quot;Any Name&quot;&gt;
        ///  &lt;Package name=&quot;Mission One&quot;&gt;
        ///    &lt;Container name=&quot;Some Words&quot;&gt;
        ///      &lt;Key ID=&quot;str_myTag_Yes&quot;&gt;
        ///        &lt;Original&gt;yes&lt;/Original&gt;
        ///        &lt;English&gt;yes&lt;/English&gt;
        ///        &lt;Czech&gt;ano&lt;/Czech&gt;
        ///        &lt;French&gt;oui&lt;/French&gt;
        ///        &lt;German&gt;ja&lt;/German&gt;
        ///        &lt;Italian&gt;sì&lt;/Italian&gt;
        ///        &lt;Polish&gt;tak&lt;/Polish&gt;
        ///        &lt;Portuguese&gt;sim&lt;/Portuguese&gt;
        ///        &lt;Russian&gt;да&lt;/Russian&gt;
        ///        &lt;Spanish&gt;sí&lt;/Spanish&gt;
        ///        &lt;Korean&gt;네&lt;/Korean&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stringtable {
            get {
                return ResourceManager.GetString("stringtable", resourceCulture);
            }
        }
    }
}
